### PR TITLE
add coralogix notifier

### PR DESCRIPTION
**Pull request by ofirshmuel**
*Issue #, if available:*

*Description of changes:*
In this PR I want to add a new notifier for Coralogix.

This tool can be used to send logs to Coralogix endpoints when an AWS Health event happens by using AWS Lambda and Amazon CloudWatch Events.
Today, over 10,000 DevOps and Security engineers around the world use Coralogix daily to monitor their stacks and fix production problems faster.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ofirshmuel** [comment]
@tipuq @slavhate Any updates?

**Review by tipuq — CHANGES_REQUESTED** [review]
Consider using https://aws.amazon.com/blogs/compute/sharing-secrets-with-aws-lambda-using-aws-systems-manager-parameter-store/ for future improvements for keys. 

The URL needs to be updated to https://aws-health-tools-assets.s3.amazonaws.com/cloudformation-templates/coralogix-notifier.json

**Comment by ofirshmuel** [comment]
@tipuq as like many other shippers, we are using private keys as environments variables.
In addition, the URL of coralogix-notifier has been update

**Review by tipuq — APPROVED** [review]

**Comment by ofirshmuel** [comment]
hi @tipuq , thanks for the merge, can you please update the JSON in this URL to the latest version 
https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/new?stackName=CoralogixNotifier&templateURL=https://aws-health-tools-assets.s3.amazonaws.com/cloudformation-templates/coralogix-notifier.json

**Comment by tipuq** [comment]
Updated

**Pull request merged**
